name: chat_flutter_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  alphasow_ui: ^1.11.0

  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  chat_app_package:
    path: ../

  cupertino_icons: ^1.0.8
  faker: ^2.2.0
  firebase_core: ^4.0.0
  firebase_storage: ^13.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^2.4.4
  image_picker: ^1.1.2
  logger: ^2.4.0
  path_provider: ^2.1.4
  record: ^6.0.0

dev_dependencies:
  build_runner: ^2.5.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.8
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
