analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/*.mocks.dart"
    - "**/*.gen.dart"
  errors:
    lines_longer_than_80_chars: ignore
    document_ignores: ignore
    prefer_constructors_over_static_methods: ignore
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
