name: tchat_app
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.6.0
  freezed: ^3.2.0
  json_serializable: ^6.8.0
  test: ^1.24.0
  very_good_analysis: ^9.0.0
