name: chat_app_package
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1
  flutter: ">=3.24.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  firebase_database: ^11.1.4
  freezed_annotation: ^2.4.4
  isar:
    hosted: https://pub.isar-community.dev
    version: ^3.1.8
  isar_flutter_libs:
    hosted: https://pub.isar-community.dev
    version: ^3.1.8
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  logger: ^2.6.1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.7
  isar_generator:
    hosted: https://pub.isar-community.dev
    version: ^3.1.8
  json_serializable: ^6.8.0
  test: ^1.24.0
  very_good_analysis: ^9.0.0
