name: dayder_chat
description: A starting point for Dart libraries or applications.
version: 1.0.1
homepage: https://github.com/alpha-sow/alphasow-ui/blob/main/README.md
repository: https://github.com/alpha-sow/alphasow-ui
documentation: https://github.com/alpha-sow/alphasow-ui/blob/main/README.md
publish_to: https://repo.alphasow.dev/artifactory/api/pub/repo-pub

environment:
  sdk: ^3.8.1
  flutter: ">=3.24.0"

# Add regular dependencies here.
dependencies:
  alphasow_ui: ^1.16.1
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  faker: ^2.2.0
  firebase_database: ^12.0.0
  firebase_storage: ^13.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  logger: ^2.6.1
  path: ^1.9.0
  path_provider: ^2.1.5
  record: ^6.0.0
  shared_preferences: ^2.3.2
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^3.0.0-0.0.dev
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  test: ^1.24.0
  very_good_analysis: ^9.0.0
