// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF6OYd5py9_b8HZcbWnfhbRO_T_q34D3A',
    appId: '1:899134203705:web:f598512d36da9b17baaae8',
    messagingSenderId: '899134203705',
    projectId: 'chat-app-3dd2e',
    authDomain: 'chat-app-3dd2e.firebaseapp.com',
    storageBucket: 'chat-app-3dd2e.firebasestorage.app',
    measurementId: 'G-T2XEX86EWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCglAxsA5Yu0E_iMTGW1dSg6wAXAx6_8xQ',
    appId: '1:899134203705:android:5a5572618ff2f4fbbaaae8',
    messagingSenderId: '899134203705',
    projectId: 'chat-app-3dd2e',
    storageBucket: 'chat-app-3dd2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtrCk8KVDbI4_iHJE21ZZKwP9LVoslRVY',
    appId: '1:899134203705:ios:866943ee5fedb79ebaaae8',
    messagingSenderId: '899134203705',
    projectId: 'chat-app-3dd2e',
    storageBucket: 'chat-app-3dd2e.firebasestorage.app',
    iosBundleId: 'com.example.chatFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtrCk8KVDbI4_iHJE21ZZKwP9LVoslRVY',
    appId: '1:899134203705:ios:866943ee5fedb79ebaaae8',
    messagingSenderId: '899134203705',
    projectId: 'chat-app-3dd2e',
    storageBucket: 'chat-app-3dd2e.firebasestorage.app',
    iosBundleId: 'com.example.chatFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF6OYd5py9_b8HZcbWnfhbRO_T_q34D3A',
    appId: '1:899134203705:web:0b79559831f3a697baaae8',
    messagingSenderId: '899134203705',
    projectId: 'chat-app-3dd2e',
    authDomain: 'chat-app-3dd2e.firebaseapp.com',
    storageBucket: 'chat-app-3dd2e.firebasestorage.app',
    measurementId: 'G-92WB8TNEWB',
  );
}
